docs: Add readme on how to build V-Ray conda package
aws-deadline/deadline-cloud-samples pull request #45
Opened 2024-11-12 23:35 UTC by AlexTranAmz

### What was the problem/requirement? (What/Why)
We want to have clear instruction on how customers could use V-Ray conda recipe we provide to build conda package
### What was the solution? (How)
Add a README.md to lay out some instruction specifically for V-Ray
### What is the impact of this change?
We have better instruction to better guide customers to successfully build V-Ray conda package
### How was this change tested?
N/A since this is only a README.md update

### Was this change documented?

Yes

---

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-11-12 23:53 UTC, mwiebe requested changes

2024-11-12 23:53 UTC, mwiebe commented on conda_recipes/vray/README.md
> +# Maya 2024 conda build recipe
nit: Need to update this title.

2024-11-13 00:02 UTC, AlexTranAmz commented on conda_recipes/vray/README.md
> +# Maya 2024 conda build recipe
Changed!

2024-11-13 04:07 UTC, mwiebe approved these changes

2024-11-13 15:59 UTC, epmog approved these changes

2024-11-13 16:28 UTC, merged